;		WuWa Mobile Config for Version 3.2
; 		    Last Modified by: Arglax
; ============================================================
; 			High-End Config
; Link: https://github.com/Arglax/Mobile-WuWa-Config/blob/main/%5BV3.x%5D%20Working%20Configs/High-Visual%20Config/Engine.ini
; ============================================================
; 		[ChangeLog] – Latest Update
; April 1, 2026 (Optional Patch)
; 1. Fixed floating grass: added r.StaticMeshLODDistanceScale=1.0
; March 22, 2026 (RECOMMENDED PATCH)
; 1. Fixed frame gen issue
; ============================================================
; 			References Used:
; 1. CVars Dump by em00se 		(https://pastebin.com/ewk6wz9W)
; 2. Cleaned Dump by AlteriaX/Brandy 	(https://pastebin.com/KUNNVZeC)
; 3. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; 4. RGCloud's 150kb Config 		(Only for the Honami Escalator inspo)
; 5. MyaMya's Config			(Discord, #config-for-testing)
; 6. Eggsee/Exie's Config		(Based on derivatives from shared community)
; ====================END OF MAIN NOTES=======================

[SystemSettings]
r.KuroFI.Enable=1
Kuro.Blueprint.EnableGameBudget=0
r.Kuro.KuroBloomStreak=1      
r.StencilForLODDither=1
r.StencilLODMode=1
r.AllowPrecomputedVisibility=1

;============================================
;	  	 Lightshafts
;============================================ 
r.LightShaftQuality=1
r.LightShaftAllowTAA=1
r.LightShaftDownSampleFactor=2
r.LightShaftBlurPasses=3
r.LightShaftNumSamples=12
r.LightShaftFirstPassDistance=0.1
r.LightShaftRenderToSeparateTranslucency=1
r.MobileLightShaft=1
r.MobileLightShaft.AllowTAA=0
r.MobileLightShaft.BloomScale=0.7
r.MobileLightShaft.DownSampleFactor=1.0
r.MobileLightShaft.NumSamples=12
r.MobileLightShaft.UseLocalLightShaft=1

;============================================
;       Screen Space Reflections/GI
;============================================ 
r.SSR.Quality=4	
r.SSR.MaxRoughness=1.0
r.SSR.Temporal=1
r.SSR.HalfResSceneColor=1
r.SSR.ExperimentalDenoiser=1
r.SSR.Stencil=1
r.SSR.TiledComposite=1
r.SSGI.Enable=1
r.SSGI.Quality=2
r.SSGI.HalfRes=1
r.ReflectionEnvironment=1
r.ReflectionEnvironmentBeginMixingRoughness=0.1
r.ReflectionEnvironmentEndMixingRoughness=0.3
r.ReflectionEnvironmentLightmapMixing=1
r.ReflectionCaptureResolution=128
r.ReflectionCaptureSupersampleFactor=2
r.RefractionQuality=1
r.Mobile.UseScreenPassSSR=1
r.Mobile.EnableLandscapeSSR=1
r.Mobile.SceneObjMobileSSR=1
r.Mobile.SSRLowPrecisionDepth=1
;============================================
;	 	  Shadows
;============================================
r.ShadowQuality=4
r.Shadow.CSM.MaxCascades=8
r.Shadow.CSM.MaxMobileCascades=8
r.Shadow.CSMDepthBias=8.0
r.Shadow.CSM.SlopeScaleDepthBias=4.0
r.Shadow.CSMSplitPenumbraScale=0.7
r.Shadow.CSM.TransitionScale=1.0
r.Shadow.DistanceScale=1.0
r.Shadow.RadiusThreshold=0.005
r.Shadow.RadiusThresholdOverrideEnable=1
r.Shadow.MinResolution=256
r.Shadow.PerObject=1
r.CapsuleShadows=1
r.CapsuleDirectShadows=1
r.CapsuleIndirectShadows=1
r.CapsuleKuroAO=1
r.CapsuleShadowsFullResolution=0
r.Shadow.StencilCulling=1
r.Shadow.StencilOptimization=1
r.Mobile.AllowDistanceFieldShadows=1
r.Mobile.AllowDitheredLODTransition=1
;============================================
;		 Lighting and GI
;============================================
r.Kuro.GlobalLightQuality=3
r.Kuro.GlobalGIRenderQuality=3
r.SkylightIntensityMultiplier=0.75
r.SkyLightingQuality=1
r.Kuro.EnableAtmosphereLightDirection=1
; ============================================================
; 		    Water & Reflections
; ============================================================
r.Water.SingleLayer=1
r.Water.SingleLayer.SSR=1
r.Water.SingleLayer.SSRTAA=1
r.Water.SingleLayer.TiledComposite=1
r.Water.SingleLayer.RefractionDownsampleFactor=2
r.Mobile.WaterSSR=1
r.Mobile.WaterSSRResDiv=2.0
r.Mobile.WaterSSRStep=64
; ============================================================
; 		Foliage, Grass & Landscape
; ============================================================
foliage.DensityScale=0.5
grass.densityScale=0.5
grass.DiscardDataOnLoad=0
r.StaticMeshLODDistanceScale=1.0
; ============================================================
; 			Anisotropic Filtering
; ============================================================
r.AnisotropicMaterials=1
r.MaxAnisotropy=16

; ============================================================
; 			Fog & Weather
; ============================================================
r.Fog=1
r.Mobile.Fog=1
r.ExponentialHeightFog=0
r.VolumetricFog=1

; ============================================================
; 			Disabled Effects
; ============================================================
r.DefaultFeature.MotionBlur=0
r.MotionBlurQuality=0
r.DepthOfFieldQuality=0
r.SceneColorFringeQuality=0
r.FastBlurThreshold=0
r.FilmGrain=0
r.TranslucencyVolumeBlur=0
r.EyeAdaptationQuality=0
r.Tonemapper.GrainQuantization=0
r.VSync=0
; ============================================================
; 				Misc
; ============================================================
t.MaxFPS=120
r.Color.Mid=0.48
r.TonemapperGamma=1.90

[/Script/Engine.RendererSettings]
;============================================
; 	FX System async optimizations
;============================================
FX.AllowAsyncTick=1
FX.BatchAsync=1
FX.BatchAsyncBatchSize=32
FX.EarlyScheduleAsync=1

;============================================
; 	Mesh distance fields generation and grass
;============================================
r.GenerateMeshDistanceFields=1
r.Kuro.Foliage.MobileGrassCullDistanceMax=30000
r.Kuro.Foliage.MobileGrass3_0CullDistanceMax=30000
r.Kuro.Foliage.MobileNearCullDistanceMax=30000 
r.Kuro.Foliage.MobileMiddleCullDistanceMax=60500
r.Kuro.Foliage.MobileSuperFarCullDistanceMax=85000 
r.Kuro.Foliage.MobileImpostorFarCullDistanceMax=205000
foliage.LODDistanceScale=4
;============================================
; 		    Kuro
;============================================
r.Kuro.InteractiveLeavesForceMobilePreview=1

;============================================
; Other performance/optimization flags
;============================================
r.DontLimitOnBattery=1

[/Script/Engine.StreamingSettings]
s.AsyncLoadingTimeLimit=4.0
s.PriorityAsyncLoadingExtraTime=20.0

[Core.Log]
Puerts=none
LogJson=none
LogCsMobile=none
LogTpMobile=none

[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/ThirdParty/ImpostorBaker/Content
Paths=../../../Engine/Plugins/json2struct/Content
Paths=../../../Engine/Plugins/Experimental/FieldSystemPlugin/Content
Paths=../../../Client/Plugins/LGUI/LGUI/Content
Paths=../../../Engine/Plugins/PrefabSystem/Content
Paths=../../../Engine/Plugins/FX/Niagara/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplay/Content
Paths=../../../Client/Plugins/Puerts/Puerts/Content
Paths=../../../Client/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
Paths=../../../Client/Plugins/CrashSight/Content
Paths=../../../Engine/Plugins/ThirdParty/QuickEditor/Content
Paths=../../../Client/Plugins/Sharphereal/Content
Paths=../../../Engine/Plugins/Experimental/GeometryProcessing/Content
Paths=../../../Client/Plugins/Kuro/TASdkPlugin/Content
Paths=../../../Engine/Plugins/rdLODtools/Content
Paths=../../../Client/Plugins/AudioMaterialPlugin/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/DLSS/Content
Paths=../../../Engine/Plugins/Runtime/HoudiniEngine/Content
Paths=../../../Client/Plugins/Kuro/KuroHotPatch/Content
Paths=../../../Client/Plugins/Kuro/KuroImposter/Content
Paths=../../../Client/Plugins/Kuro/KuroAutomationTool/Content
Paths=../../../Engine/Plugins/FX/HoudiniNiagara/Content
Paths=../../../Client/Plugins/LogicDriverLite/Content
Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
Paths=../../../Engine/Plugins/Experimental/ControlRig/Content
Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
Paths=../../../Engine/Plugins/SequenceDialogue/Content
Paths=../../../Client/Plugins/Puerts/ReactUMG/Content
Paths=../../../Client/Plugins/genesis-ue-plugin/RenderExporter/Content
Paths=../../../Engine/Plugins/KuroiOSDelegate/Content
Paths=../../../Client/Plugins/Kuro/KuroCloudGame/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplayUI/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/OpacityMicroMap/Content
Paths=../../../Client/Plugins/BlockoutToolsPlugin/Content
Paths=../../../Client/Plugins/ComfyTextures/Content
Paths=../../../Client/Plugins/KuroComputeShader/Content
Paths=../../../Client/Plugins/KuroTDM/Content
Paths=../../../Client/Plugins/Kuro/ImposterBaker/Content
Paths=../../../Client/Plugins/Kuro/KuroGachaTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPSOTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPushSdk/Content
Paths=../../../Client/Plugins/SdkParamExtend/Content
Paths=../../../Client/Plugins/SpinePlugin/Content
Paths=../../../Client/Plugins/TpSafe/Content
Paths=../../../Engine/Plugins/AFME/Content
Paths=../../../Engine/Plugins/Animation/ACLPlugin/Content
Paths=../../../Engine/Plugins/AssetChecker/Content
Paths=../../../Engine/Plugins/AssetMemoryAnalyzer/Content
Paths=../../../Engine/Plugins/DawnSDK/DawnSDK/Content
Paths=../../../Engine/Plugins/Dawn/Content
Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
Paths=../../../Engine/Plugins/GSR/Content
Paths=../../../Engine/Plugins/MFRCModule/Content
Paths=../../../Engine/Plugins/Runtime/Intel/XeSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/NRD/Content
Paths=../../../Engine/Plugins/Runtime/Water/Content