;		WuWa Mobile Config for Version 3.1
; 		    Last Modified by: Arglax
; ============================================================
; 			Performance Config (Config_2)
; Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Performance%20Configs/Config_2/Engine.ini
; ============================================================
; February 24, 2026
; 1. Created the config.
;_____________________________________________________________
; 			Final Notes
; 1. Plug-and-Play
; ============================================================
; 			References Used:
; 1. Unreal Engine 4.27 Console Variables and Commands 
;	(https://framedsc.com/GeneralGuides/ue4_commands.htm)
; 2. UE Official CVar Reference 	
;	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; ====================END OF MAIN NOTES=======================

[SystemSettings]
r.HZBOcclusion=1
r.DefaultBackBufferPixelFormat=0
r.TonemapperGamma=1.95
r.Color.Mid=0.45

FX.AllowAsyncTick=1
FX.AllowCulling=1
FX.AllowFastPathFunctionLibrary=1
FX.AllowGPUParticles=1
FX.AllowGPUSorting=1
FX.BatchAsync=1
FX.BatchAsyncBatchSize=32

r.Mobile.SupportsGen4TAA=1
r.Mobile.AntiAliasing=2
r.TemporalAA.HistoryScreenPercentage=125
r.TemporalAA.Mobile.UseCompute=1
r.TemporalAA.Quality=2
r.TemporalAA.R11G11B10History=1
r.TemporalAA.Upsampling=1
r.TemporalAA.Upscaler=1
r.TemporalAA.UseMobileConfig=1
r.TemporalAACatmullRom=1
r.TemporalAACurrentFrameWeight=0.16
r.TemporalAAFilterSize=1.0
r.TemporalAAPauseCorrect=1
r.TemporalAASamples=16

;0 = more accurate shadow rendering, 1 = cache, better for perf
r.Shadow.CSMCaching=0
r.Shadow.CacheWPOPrimitives=0

r.Shadow.CachePreshadow=1
r.Shadow.CacheWholeSceneShadows=1
r.Shadow.ConservativeBounds=1
r.Shadow.CSM.MaxCascades=8
r.Shadow.CSM.MaxMobileCascades=8
r.Shadow.CSM.TransitionScale=1.5
r.Shadow.CSMDepthBias=10
r.Shadow.CSMReceiverBias=0.8
r.Shadow.Denoiser=2
r.Shadow.Denoiser.HistoryConvolutionSamples=4
r.Shadow.Denoiser.MaxBatchSize=4
r.Shadow.Denoiser.PreConvolution=2
r.Shadow.Denoiser.ReconstructionSamples=8
r.Shadow.DistanceScale=0.80
r.Shadow.EnableModulatedSelfShadow=1
r.Shadow.FilterMethod=0
r.Shadow.MaxCSMResolution=2
r.Shadow.MaxNumFarShadowCascades=4
r.Shadow.MaxResolution=1536
r.Shadow.MinResolution=1024
r.Shadow.PerObject=1
r.Shadow.RadiusThreshold=0.0001
r.ShadowQuality=5

[/Script/Engine.RendererSettings]
r.Android.DisableVulkanSupport=0
r.Mobile.AllowDistanceFieldShadows=1

[/Script/Engine.GarbageCollectionSettings]
gc.ActorClusteringEnabled=1
gc.AllowParallelGC=1
gc.BlueprintClusteringEnabled=1
gc.CreateGCClusters=1
gc.FlushStreamingOnGC=0
gc.ForceCollectGarbageEveryFrame=0
gc.IncrementalBeginDestroyEnabled=1
gc.IncrementalGCTimePerFrame=1

[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/ThirdParty/ImpostorBaker/Content
Paths=../../../Engine/Plugins/json2struct/Content
Paths=../../../Engine/Plugins/Experimental/FieldSystemPlugin/Content
Paths=../../../Client/Plugins/LGUI/LGUI/Content
Paths=../../../Engine/Plugins/PrefabSystem/Content
Paths=../../../Engine/Plugins/FX/Niagara/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplay/Content
Paths=../../../Client/Plugins/Puerts/Puerts/Content
Paths=../../../Client/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
Paths=../../../Client/Plugins/CrashSight/Content
Paths=../../../Engine/Plugins/ThirdParty/QuickEditor/Content
Paths=../../../Client/Plugins/Sharphereal/Content
Paths=../../../Engine/Plugins/Experimental/GeometryProcessing/Content
Paths=../../../Client/Plugins/Kuro/TASdkPlugin/Content
Paths=../../../Engine/Plugins/rdLODtools/Content
Paths=../../../Client/Plugins/AudioMaterialPlugin/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/DLSS/Content
Paths=../../../Engine/Plugins/Runtime/HoudiniEngine/Content
Paths=../../../Client/Plugins/Kuro/KuroHotPatch/Content
Paths=../../../Client/Plugins/Kuro/KuroImposter/Content
Paths=../../../Client/Plugins/Kuro/KuroAutomationTool/Content
Paths=../../../Engine/Plugins/FX/HoudiniNiagara/Content
Paths=../../../Client/Plugins/LogicDriverLite/Content
Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
Paths=../../../Engine/Plugins/Experimental/ControlRig/Content
Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
Paths=../../../Engine/Plugins/SequenceDialogue/Content
Paths=../../../Client/Plugins/Puerts/ReactUMG/Content
Paths=../../../Client/Plugins/genesis-ue-plugin/RenderExporter/Content
Paths=../../../Engine/Plugins/KuroiOSDelegate/Content
Paths=../../../Client/Plugins/Kuro/KuroCloudGame/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplayUI/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/OpacityMicroMap/Content
Paths=../../../Client/Plugins/BlockoutToolsPlugin/Content
Paths=../../../Client/Plugins/ComfyTextures/Content
Paths=../../../Client/Plugins/KuroComputeShader/Content
Paths=../../../Client/Plugins/KuroTDM/Content
Paths=../../../Client/Plugins/Kuro/ImposterBaker/Content
Paths=../../../Client/Plugins/Kuro/KuroGachaTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPSOTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPushSdk/Content
Paths=../../../Client/Plugins/SdkParamExtend/Content
Paths=../../../Client/Plugins/SpinePlugin/Content
Paths=../../../Client/Plugins/TpSafe/Content
Paths=../../../Engine/Plugins/AFME/Content
Paths=../../../Engine/Plugins/Animation/ACLPlugin/Content
Paths=../../../Engine/Plugins/AssetChecker/Content
Paths=../../../Engine/Plugins/AssetMemoryAnalyzer/Content
Paths=../../../Engine/Plugins/DawnSDK/DawnSDK/Content
Paths=../../../Engine/Plugins/Dawn/Content
Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
Paths=../../../Engine/Plugins/GSR/Content
Paths=../../../Engine/Plugins/MFRCModule/Content
Paths=../../../Engine/Plugins/Runtime/Intel/XeSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/NRD/Content
Paths=../../../Engine/Plugins/Runtime/Water/Content
Paths=../../../Client/Plugins/Kuro/KRDataAnalyticsPlugin/Content
Paths=../../../Engine/Plugins/Experimental/ColorCorrectRegions/Content
Paths=../../../Client/Plugins/Kuro/KuroDynamicMeshBatch/Content
Paths=../../../Client/Plugins/Kuro/KuroPerfCat/Content
Paths=../../../Client/Plugins/MagtModule/Content
Paths=../../../Engine/Plugins/MagicDawn/Content