;Change "GPUNAME" with the one in your Client.Log's "selected device profile"
;Mobile Tutorial: https://youtube.com/shorts/ygf6GUBkx18
;PC Tutorial: https://youtu.be/gtmyFKGyl1M

[Android_GPUNAME DeviceProfile]
DeviceScore=5000
CVars=r.Mobile.DeviceEvaluation=3
CVars=r.MobileContentScaleFactor=1.0
CVars=r.SecondaryScreenPercentage.GameViewport=100.00
CVars=r.MFRC.Enable=1
Cvars=r.DetailMode=3
CVars=r.MaterialQualityLevel=3
Cvars=r.KuroMaterialQualityLevel=2
CVars=r.Android.DisableVulkanSupport=0
CVars=r.Vulkan.RobustBufferAccess=1